## Introduction into Background of numpy
### what is Numpy ?
#### numpy is a multidimensional array library---> it can be used to store all sorts of data like 1D,2D and 3D etc

### Whys use Numpy over Lists?
#### Lists are very slow and Numpy are very fast.
#### Numpy uses fixed type 
    example: lets assume 5 it is stored in binary- 00000101 and in numpy it can be in int8(1byte),int16(2B),int32(3B),etc
#### List is a built in int type in python
    it uses size,Reference count ,object type , object value, and it uses large space to store the data
#### Numpy is faster because it is faster to read less bytes of memory
#### no type checking when iterating through objects
#### Numpy is faster because it uses contigious memory
     BENIFITS:1)our computer uses SIMD Vector Processing units (Single Instruction Multiple Data)
              2) Effective cache utilization

## Applications of numpy

### Can do Mathematics(MATLAB Replacement)
### Plotting
### Backend(Pandas,connect 4,Digital Photography)
### important for Machine Learning directly or Indirectly (eg in Tensorflow)

In [82]:
# for more information on numpy Vs Lists
# https://jakevdp.github.io/blog/2014/05/09/why-python-is-slow/

## Loading Numpy

In [1]:
import numpy as np

### The Basics

In [2]:
a = np.array([1,2,3]) # Loading 1 Dimensional Array
a

array([1, 2, 3])

In [4]:
b = np.array([[4.0,5.0,6.0],[8.0,4.0,6.0]]) # Loading 2D array
b

array([[4., 5., 6.],
       [8., 4., 6.]])

In [5]:
# Get Dimension
a.ndim

1

In [6]:
b.ndim

2

In [7]:
# Geting shape
a.shape  # shape gives rows and columns

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
# Getting the data type
a.dtype   ## default value is int 32 

dtype('int32')

In [10]:
 # we can also change the data type 
a = np.array([1,2,3],dtype='int16')
a.dtype

dtype('int16')

In [11]:
# Get size
a.itemsize

2

In [13]:
a.size # gives bytes stored

3

In [14]:
# get total size
a.nbytes
#a.nbytes = a.itemsize*a.size

6

In [15]:
b.nbytes ## floats are bigger than integer

48

## Accesing/Changing specific elements,rows,columns etc

In [17]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [19]:
a.shape

(2, 7)

In [21]:
# Getting a specific elemet [rows, columns]
# eg:13

a[1,5]

13

In [22]:
# Getting a specific row
a[:,2]

array([ 3, 10])

In [24]:
# getting little more fancy stuff [start index:end index:stepsize]
# eg: 2,4,6
a[0,1:6:2]
#a[0,1:-1:2]  using negative index

array([2, 4, 6])

In [25]:
# changing the value for specific rows and columns
a[1,5]=20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [27]:
a[:,2]=20
a

array([[ 1,  2, 20,  4,  5,  6,  7],
       [ 8,  9, 20, 11, 12, 20, 14]])

In [28]:
a[:,2]=[3,10]
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

### 3-D example

In [33]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
b.ndim

3

In [35]:
b[0,1,1]

4

## Initializing Different type of Arrays

In [39]:
# Concstructing a matrix of zeros
#np.zeros is a built in function
np.zeros((2,3))  # (2,3 rows and columns)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [43]:
# All ones in Matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [44]:
# Any other matrix
np.full((2,3),44) # first it takes shape of the matrix

array([[44, 44, 44],
       [44, 44, 44]])

In [45]:
# Any other number
np.full_like(a,4) # it is taking shape of a and printing 4 in a.shape matrix

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [46]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.58479496, 0.7508788 ],
       [0.99317791, 0.94458734],
       [0.76813774, 0.16652974],
       [0.4358233 , 0.15507794]])

In [48]:
np.random.random_sample(a.shape) # if you need to take shape then we use random_sample

array([[0.50654001, 0.17029403, 0.41941593, 0.44202712, 0.84701181,
        0.95872867, 0.63074257],
       [0.76107457, 0.89950864, 0.76854055, 0.14133078, 0.46711484,
        0.94937249, 0.25245779]])

In [53]:
# Random integer number
np.random.randint(4,8,size=(4,4))

array([[4, 7, 4, 5],
       [4, 7, 4, 5],
       [4, 4, 7, 7],
       [4, 7, 5, 5]])

In [54]:
# identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [56]:
# Repeat an Array
a = np.array([[1,2,3]])
r1 = np.repeat(a,3,axis=1)
r1

array([[1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [57]:
# Creating a array like below
#[1,1,1,1,1
#1,0,0,0,1
#1,0,9,0,1
#1,0,0,0,1
#1,1,1,1,1]

In [61]:
output = np.ones((5,5))
print(output)
z= np.zeros((3,3))
print(z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [63]:
z[1,1]=9
z

array([[0., 0., 0.],
       [0., 9., 9.],
       [0., 0., 0.]])

In [64]:
output[1:4,1:4]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 9. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


### Be Careful when copying Arrays!!!

In [65]:
a = np.array([1,2,3])
b = a
print(b)

[1 2 3]


In [67]:
b[0]=50
print(b)
print(a) # it also actually changes value in the a

[50  2  3]
[50  2  3]


In [69]:
# hence use copy function
a = np.array([1,2,3])
b = a.copy()
b[0]=50
print(b)
print(a)

[50  2  3]
[1 2 3]


## Mathematics

In [ ]:
# https://numpy.org/doc/stable/reference/routines.math.html ---> for more information

In [70]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [71]:
a+2

array([3, 4, 5, 6])

In [72]:
a-2

array([-1,  0,  1,  2])

In [73]:
a*2

array([2, 4, 6, 8])

In [74]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [75]:
b=np.array([1,0,1,0])
b

array([1, 0, 1, 0])

In [76]:
a+b

array([2, 2, 4, 4])

In [77]:
# Taking the sine
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

### Linear Algebra

In [78]:
# https://numpy.org/doc/stable/reference/routines.linalg.html ---->for more information on linera algebra

In [81]:
a = np.ones((2,3))
print(a)

b = np.full((3,3),2)
print(b)
#a*b gives error cause not becuase of same type
# hence we use builtin function called Matrix Multiplication (matmul)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


array([[6., 6., 6.],
       [6., 6., 6.]])

## Statistics

In [83]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
stats.min()

1

In [85]:
stats.max()

6

In [93]:
stats.max(axis=1)

array([3, 6])

In [95]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [96]:
np.sum(stats)

21

## Reorganising Arrays

In [99]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(1,-1)
print(after)
#after = before.reshape(2,3) ---> gives error cause it cannot convert it into shape or shape mismatch

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [103]:
# Vertical stacking of vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
#np.vstack([v1,v2]) 
np.vstack([v1,v2,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [109]:
# horizontal stacking of vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

#### Load data from the file

In [119]:
filedata=np.genfromtxt('data.txt',delimiter=',')
#filedata # contains float values 
filedata.astype('int32') # it is used as a copy function 
#print(filedata)
filedata=filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Advanced Indexing and Boolean Masking

In [120]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [121]:
filedata[filedata>50] # for getting values of data which is greater than 50

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [124]:
# we can index with a list in numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,4,8]]

array([2, 5, 9])

In [126]:
np.any(filedata>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [127]:
np.all(filedata>50,axis=1)

array([False, False, False])

In [128]:
((filedata>50) & (filedata>100))

array([[False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [ ]:
# Thank you